name: Chat GPT PR Review

on:
    pull_request:
        branches: 
            - '**'

permissions:
    contents: read
    pull-requests: write

jobs:
    pr-review:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                
            - name: Get PR diff and run AI review
              env:
                OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                PR_NUMBER: ${{ github.event.pull_request.number }}
                PR_TITLE: ${{ github.event.pull_request.title }}
                PR_AUTHOR: ${{ github.event.pull_request.user.login }}
                REPO_OWNER: ${{ github.repository_owner }}
                REPO_NAME: ${{ github.event.repository.name }}
              run: |
                echo "Starting PR Review...."

                #Get PR Diff
                git fetch origin ${{ github.event.pull_request.base.ref }}
                DIFF=$(git diff origin/${{ github.event.pull_request.base.ref }}...HEAD)

                if [ -z "$DIFF" ]; then
                    echo "No changes detected"
                    exit 0
                fi

                #Escape the diff for JSON
                DIFF_ESCAPED=$(echo "$DIFF" | jq -Rs .)

                #Create the prompt
                PROMPT="Review this pull reqeust:

                **Title:** $PR_TITLE
                **Author:** $PR_AUTHOR

                **Changes:**
                \`\`\`diff
                $DIFF
                \`\`\`

                Provide a code review with:
                - Summary
                - Strength
                - Issues (Use Critical, Medium, Minor)
                - Suggestions
                - Testing recommendations
                
                Be specific and actionable."

                #Escape prompt for JSON
                PROMPT_ESCAPED=$(echo "$PROMPT" | jq -Rs .)

                #Call OpenAI API
                echo "Calling ChatGPT API...."
                RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
                    -H "Content-Type: application/json" \
                    -H "Authorization: Bearer $OPENAI_API_KEY" \
                    -d '{
                        "model": "gpt-5",
                        "messages": [
                            {
                                "role": "system",
                                "content": "You are an experiences software engineer reviewing code."
                            },
                            {
                                "role": "user",
                                "content": '"$PROMPT_ESCAPED"'
                            }
                            ],
                            "temperature": 0.3,
                            "max_completiontokens": 2500
                            }')

                        #Extract the review from response
                        REVIEW=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')

                        #Check for errors
                        if [ "$REVIEW" == "null" ]; then
                            ERROR=$(echo "$RESPONSE" | jq -r '.error.message')
                            echo "API Error: $ERROR"
                            REVIEW="AI Review failed: $ERROR"
                        fi

                        #Create comment body
                        COMMENT_BODY="## AI Code Review
                        
                        $REVIEW
                        
                        ---
                        *Reviewed by ChatGPT . Automated review*"

                        #Escape for JSON
                        COMMENT_ESCAPED=$(echo "$COMMENT_BODY" | jq -Rs .)

                        #Post comment to PR
                        echo "Posting comment to PR...."
                        curl -s -X POST \
                            -H "Authorization: Bearer $GITHUB_TOKEN" \
                            -H "Accept: application/vnd.github.v3+json" \
                            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$PR_NUMBER/comments \
                            -d '{"body": '"$COMMENT_ESCAPED"'}'

                        echo "Review posted successfully"




    