name: Code Quality Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint Changed Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: master
          # Configure file patterns for your language
          FILTER_REGEX_INCLUDE: '.*\.(py|js|ts|java|cpp|c|cs|go|rs|php|rb|swift|kt)$'
          FILTER_REGEX_EXCLUDE: '^(docs|vendor|third_party|node_modules|.github|.vscode|.idea|.venv|env|.env|__pycache__|build|dist|target)/.*$'
          # Enable language-specific linters (uncomment as needed)
          # Python
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_PYTHON_PYLINT: true
          # JavaScript/TypeScript
          # VALIDATE_JAVASCRIPT_ES: true
          # VALIDATE_TYPESCRIPT_ES: true
          # Java
          # VALIDATE_JAVA_CHECKSTYLE: true
          # C/C++
          # VALIDATE_CPP_CLANG: true
          # Go
          # VALIDATE_GO_GOLANGCI_LINT: true
          # Rust
          # VALIDATE_RUST_CLIPPY: true
          # PHP
          # VALIDATE_PHP_BUILTIN: true
          # Ruby
          # VALIDATE_RUBY_RUBOCOP: true
          # Swift
          # VALIDATE_SWIFT_SWIFTLINT: true
          # Kotlin
          # VALIDATE_KOTLIN_KTLINT: true
